"""
Workflow States
Defines all application states used by the workflow engine.
"""

START = "START"

SELLER_INITIATION = "SELLER_INITIATION"

BUYER_CONFIRMATION = "BUYER_CONFIRMATION"

DOCUMENTS = "DOCUMENTS"

PAYMENT = "PAYMENT"

UNDER_VERIFICATION = "UNDER_VERIFICATION"

DOCUMENT_REQUIRED = "DOCUMENT_REQUIRED"

DELAYED = "DELAYED"

COMPLETED = "COMPLETED"